### ISSUE TITLE
Mausrad funktioniert nicht mehr in der Journal-Ansicht

### ISSUE THREAD

**Issue by aisbergde** [Thomas-Mielke-Software/EasyCash#11]
In der Journal-Ansicht funktioniert das Mausrad nicht mehr (zum Scrollen), seit es am rechten Rand den Navigationsbaum gibt.
Ich bin mir zwar nicht 100% sicher, ob er früher funktionierte, denke aber schon, da ich das Mausrad immer und überall zur Navigation verwende und das wäre mir schon früher aufgefallen, wenn es nicht funktioniert hätte.

Die Pfeiltasten und Seite-hoch, Seite-runter funktionieren.

**Comment by thomiel** [comment]
Bin schon am Recherchieren, wie ich es wieder rund machen kann:

https://stackoverflow.com/questions/66120175/mfc-how-to-fix-an-mdi-after-replacing-the-cview-with-a-csplitterwnd-having-two/66127370

**Comment by thomiel** [comment]
mit https://github.com/Thomas-Mielke-Software/EasyCash/commit/2c0c5eb375771362a01ce5b0433606f903e34942 behoben
