### ISSUE TITLE
Navigationsbaum soll sich die eingestellte Breite merken, wenn man die maximierten Fenster wechselt

### ISSUE THREAD

**Issue by aisbergde** [Thomas-Mielke-Software/EasyCash#12]
Ich habe verschiedene Jahre geöffnet (maximiert), und überall das Navigationsfenster verbreitert, weil es zu schmal ist und man nur ein bis zwei Wörter lesen kann. Leider wird die Breite immer zurückgesetzt, wenn man zwischen den Fenstern wechselt.

Es sollte so sein, dass die Breite des Navigationsfensters erhalten bleibt, wenn man die Fenster wechselt, damit man damit vernünftig arbeiten kann.

Aktueller Workaround - Fenster nicht maximieren, dann bleibt die Breite erhalten.

**Comment by thomiel** [comment]
Ja, Feinschliff kommt noch.

**Comment by thomiel** [comment]
Größe der Navigations-Seitenleise wird jetzt beibehalten -- auch zwischen Programmstarts.

https://github.com/Thomas-Mielke-Software/EasyCash/commit/3c1965d742353be862ef25f06807b1a7b46929cb
