### ISSUE TITLE
Neue Navigationsleiste springt zum letzten Eintrag

### ISSUE THREAD

**Issue by Darkwing371** [Thomas-Mielke-Software/EasyCash#13]
Oh, schön das Projekt auch auf Github zu finden, gute Idee! Wir führen das hier einfach mal komplett auf deutsch, einverstanden.  ;)

Nur ein kleiner Hinweis auf einen "Schönheitsfehler" in der neuen Navigationsleiste: Wenn man in einem Monat keine Buchungen hat, wird per default zum letzten Eintrag im Journal gesprungen. Vielleicht könnte man aber besser zum nächsten Monat mit einer Buchung springen, oder ähnlich.

Also Beispiel:

Januar mit Buchungen,
Februar mit Buchungen,
März **ohne** Buchungen,
April **ohne** Buchungen,
Mai mit Buchungen, 
Juni mit Buchungen ...

Wenn ich jetzt auf März klicke, springt er zum Dezember – oder was immer der letzte Eintrag im Journal ist. Er könnte ja aber vielleicht besser zu Mai springen, oder zu Ende Februar; beides irgendwie logischer als Dezember.

Kleiner Vorschlag, nix weltbewegendes.
Danke für Deine Arbeit!

**Comment by thomiel** [comment]
Irgendeine Heuristik hatte ich da gebaut, scheint dann wohl nicht zu funktionieren... Besser vielleicht noch wäre es, die Monate ohne Buchungen in der Navigation zu disabeln.

**Comment by Darkwing371** [comment]
Klar, wenns einfacher zu machen geht, auch ne schöne Möglichkeit.

Beispielsweise ausgrauen und unklickbar machen – hübscher als wenn Monatsnamen ganz fehlen ... das müssen schon zwölf sein, sonst siehts irgendwie doof aus. 😁

**Comment by thomiel** [comment]
Ja, das wäre unschön. Leider müsste ich das Listen-Steuerelement selbst neu bauen, damit es funktioniert mit dem disablen von einzelnen Monaten, habe ich jetzt gemerkt. Das ist zu viel Aufwand.

**Comment by thomiel** [comment]
Bugfix ist in v2.42 jetzt released.
