### ISSUE TITLE
CSV-Export ohne Titelzeile

### ISSUE THREAD

**Issue by Darkwing371** [Thomas-Mielke-Software/EasyCash#14]
Hi Thomas!

Bin gerade auf diesen (sehr alten) [Thread](https://www.easyct.de/forum/viewthread.php?thread_id=64&highlight=gdpdu&pid=160#post_171) im Forum gestoßen, bei dem es um den CSV-Export der Buchungsdaten geht. 

Du meintest, in der Exportdatei sind nachher „sprechende Datenfeldbezeichnungen als Titelzeile in der CSV-Datei vorhanden“. Ich stellte aber gerade verwundert fest: das sind sie nicht.

Hat sich das in den letzten 15 Jahren irgendwann aus gutem Grund geändert oder ist das über die Zeit einfach nur unbeabsichtigt verlustig gegangen? Wäre cool, wenn was wieder drin wäre oder meinetwegen sogar in einem kleinen Export-Dialog an- und abwählbar wäre.

Dankeschön!
DW

**Comment by thomiel** [comment]
wird in v2.43 enthalten sein

https://github.com/Thomas-Mielke-Software/EasyCash/commit/7e151394a3441f15bc1cd3c4294789cf45d61089
