### ISSUE TITLE
Privatanteil (Anteil mit VST-Abzug) und (Anteil ohne VST-Abzug) vertauscht?

### ISSUE THREAD

**Issue by ardi69** [Thomas-Mielke-Software/EasyCash#17]
Hallo,
ich mag vielleicht falsch liegen.
ich habe eine Testbuchung gemacht
Ausgabe 119 € Privat-Split 10% (60%USt)
Steuer 19%
Die Ausgabenbuchung ist ok (Netto 100,00€ / VSt 19,00€ / Brutto 119,00€
es werden zwei Einnahme Buchungen erzeugt
1. Privatanteil (10,00%) (Anteil **mit** VST-Abzug)         Netto 6€ / USt 19% / USt-Betr. 1,14€
2. Privatanteil (10,00%) (Anteil **ohne** VST-Abzug)      Netto 6€ / USt 0% / USt-Betr. 0,00€

Die Buchungen sind o.k. nur der Buchungstext ist vertauscht (und verwirrend).
Buchung **2**: ist **mit** VSt Abzug da hier keine USt berechnet wird und die VSt voll abgezogen wurde
Buchung 1: vice versa

**Comment by thomiel** [comment]
Der Betrag des Vorsteuer-Abzugs ist 1,14 € -- als ist das mit. 0 € heißt ohne. Ich glaube, so ist der common sense.

**Comment by ardi69** [comment]
Sorry. Der Privatanteil wird als Einnahmen mit Ust 1.14€ gebucht. Da sich die USt mit der anteiligen VSt aufhebt ist der Privatanteil ohne VSt-Abzug
Bei der anderen Buchung ist der Privatanteil ohne USt also mit VSt-Abzug.

PS: Was soll das eigentlich. Welcher Privatanteil erlaubt einen VSt-Abzug.

**Comment by thomiel** [comment]
Z.B. bei der sog. 1%-Regel für KFZ-Kosten: https://www.haufe.de/finance/buchfuehrung-kontierung/private-pkw-nutzung/1-regelung-berechnung-umsatzsteuerpflichtiger-unternehmer_186_410342.html

Einfach vertauschen ist aber auch nicht richtig. Die Vorsteuer ist ja tatsächlich zu 100% abziehbar, lediglich die als Privatanteil herbeiphantasierte USt. ist in diesem Fall nur zu 80% anzurechnen.

**Comment by ardi69** [comment]
Mit Verlaub, das ist Unsinn. 
Bei der 1%-Regel werden monatlich 1% des Listenpreis als Umsats/Einnahme gebucht. Und das unabhängig von irgend welchen Ausgaben. Da Kfz- Kosten sowohl mit als auch ohne USt (z.B. Versicherung oder Kfz-Steuer) sein können, werden nur 80% der USt unterworfen. 
Alle Kfz-Kosten werden so gebucht wie sie sind (keine Split-Buchung o.ä.) mit vollem VSt-Abzug.
Wenn ich Blödsinn schreibe, dann entschuldige ich für das "Unsinn"

**Comment by thomiel** [comment]
Ich persönlich würde Worte wie "Unsinn" oder "Blödsinn" für Situationen aufsparen, wo man nicht mehr wirklich miteinander diskutiert bzw. nicht mehr versucht die Prämissen des Gegenübers zu verstehen. Wir sind beide nur Menschen und machen potenziell Fehler.

Ich sehe eigentlich keinen Widerspruch zwischen den beiden letzten posts:

    "Die Vorsteuer ist ja tatsächlich zu 100% abziehbar" == "Alle Kfz-Kosten werden so gebucht wie sie sind (keine Split-Buchung o.ä.) mit vollem VSt-Abzug."
    "USt. ist in diesem Fall nur zu 80% anzurechnen." == "werden nur 80% der USt unterworfen"

Wäre es nicht so ein unzumutbarer antiker Code, würde ich ja sagen "mach einen pull request":
https://github.com/Thomas-Mielke-Software/EasyCash/blob/master/buchendlg.cpp#L583
https://github.com/Thomas-Mielke-Software/EasyCash/blob/master/buchendlg.cpp#L660

Dann könnten wir uns die Umständlichkeiten der deutschen Sprache sparen :)

**Comment by ardi69** [comment]
Hallo Thomas,
Ich entschuldige mich in aller Form. Ich habe mich im Ton vergriffen. Ist eigentlich nicht meine Art. Es war gestern auch spät.
In der Tat hab ich versucht EC&T zu compilieren (mit VS 2017). Es kamen aber zu viele Warnungen/Fehler. Leider hast du auch beim letzten commit die neuen Dateien vergessen.
Die graflib würde ich mit gdiplus ersetzen. Nur so nebenbei.
LG Armin

**Comment by thomiel** [comment]
Cool. Ich hatte es auch mal mit VS2017 probiert und bin in compiler errors ertrunken. Letztens habe ich ein anderes größeres VS2009-Projekt auf VS2022 portiert. Scheint als hätte Microsoft einiges an Arbeit in den Migrationsassistenten gesteckt. Jedenfalls war das überschaubarer Aufwand. Plane deshalb einen VS2022-Branch, der in EC&T v3.0 münden soll.

Ja, ist gerade ein bisschen work-in-progress. So lange ich bei EC&T als Einzelkämpfer unterwegs bin, spare ich mir ein echtes Branching-Model. Welche Dateien fehlen?

Wenn Dir für die Split-Buchungstexte eine sinnvollere Alternative einfällt, nur raus damit!

**Comment by thomiel** [comment]
Hi Armin! Ich habe heute mal einen branch _**vs2022v143**_ angelegt, der mit Visual Studio 2022 preview einigermaßen funktioniert. Einzig bei MainFrame.cpp müsste das deprecatete `std::auto_ptr` ersetzt werden. (Würde VS2022 einfach mal ein MFC-Projekt mit Ribbon-Oberfläche aus ner Template erzeugen lassen, um zu sehen, was der Stand der Technik ist.) Bin offen für PRs, wenn Du Lust auf einen kleinen intellektuellen Snak hast.

Ich habe es im Moment nur so weit vorangetrieben, dass ich das ActiveX von EC&T als 64-bit-Version bauen konnte, damit ich ein Plugin im Dialog-Designer von VS2022 öffnen kann, das ja inzwischen 64-bit ist.

Ich schließe den Issue dann erst mal.
