### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by maddin200** [Thomas-Mielke-Software/EasyCash#3]
/MyInternetSession.cpp line 70

und line 87

return; // zuviel ?

**Comment by thomiel** [comment]
MyInternetSession war tatsächlich toter code und gar nicht mehr in der Projektdatei enthalten. Habe ich jetzt in https://github.com/Thomas-Mielke-Software/EasyCash/commit/6574323c5afd197d4ced789af10338f451b04325 entfernt.
