### ISSUE TITLE
Elster - wo findet man ausführlichere Protokolle, insbesondere die Serverantwort im Fall eines Fehlers?

### ISSUE THREAD

**Issue by aisbergde** [Thomas-Mielke-Software/EasyCash#7]
Ich bekomme heute beim Versuch, Umsatzsteuer-Voranmeldungen zu verschicken, immer solche Fehler:
![](https://i.imgur.com/KXeLMeS.png)
Der Elster-Annahmeserver hat einen Fehler gemeldet. blablabla

Gibt es die Möglichkeit, die genaue Serverantwort anzuschauen? Wird diese irgendwo protokolliert oder könnte man das einbauen, dass diese Antwort im Falle eines Elster-Fehlers protokolliert wird?

Falls man nun Elster-Übertragungen außerhalb EasyCash vornehmen würde, wie bekommt man dann die Informationen dazu in das EasyCash rein, damit dann alle Auwertungen stimmen, oder ist das gar nicht nötig, weil vielleicht EasyCash gar nicht auswertet, ob und was per Elster übertragen wurde?

**Comment by thomiel** [comment]
Das wäre eric.log im Verzeichnis C:\Users\{Benutzername}\AppData\Local\Temp. Mehr dazu [hier](https://www.easyct.de/forum/viewthread.php?thread_id=4047).

**Comment by aisbergde** [comment]
OK, ich musste die neue Version des Plugins noch mal manuell herunterladen und installieren, jetzt funktioniert alles.
Soll zukünftig hier der Bugtracker oder doch eher das Forum genutzt werden für Bugs? Oder beides?
Im Forum war ja schon alles beschrieben und gelöst!
Danke für den schnellen Support und die schnelle neue Version!!!

**Comment by thomiel** [comment]
Einen extra Bugtracker will ich auf jeden Fall neben dem Forum haben, bin noch unentschieden, ob ich mir wegen Datenschutzerwägungen einen eigenen Zammad aufsetze oder das GitHub hier weiter nutzen soll...
