### ISSUE TITLE
Formular Umsatzsteuer: Vorauszahlungen werden falsch in Formular übernommen: manchmal 1 EUR zu viel

### ISSUE THREAD

**Issue by aisbergde** [Thomas-Mielke-Software/EasyCash#8]
Ich mache gerade die Umsatzsteuer-Erklärung für meine Frau, dabei fällt mir auf, dass Daten zur Vorauszahlung manchmal falsch in das Formular übernommen werden, bei einigen Einträgen wird ein EUR zu viel übernommen.
Mir scheint, dass bei der Übernahme der EUR-Betrag gerundet wird (in dem Fall aufgerundet), der Nachkomma-Betrag wird dann aber korrekt genommen.

Beispiel:
Im Journal 295,54
Im Formular wird daraus 296,54 (ein EUR zu viel)

Das führt dazu, dass die Vorauszahlungen ein wenig falsch ausgefüllt werden.

**Comment by thomiel** [comment]
Kurios! Da in den Voranmeldungsformularen bei den Bemessungsgrundlagen auf ganze € abgerundet wird, sollten die Vorauszahlungen eigentlich niedriger sein als im Journal.

Es kann natürlich sein, dass wenn eine Buchung geändert wurde, für die bereits eine Voranmeldung abgegeben wurde, die USt.-Erklärung differiert. Ohne die Zahlen im Einzelnen zu kennen, kann ich schwer sagen, woher die Differenz nun wirklich kommt. Es ist aber ganz normal, dass USt.-Erklärung und die Voranmeldungen differieren.

**Comment by aisbergde** [comment]
![Journal](https://i.imgur.com/jZdjdUr.png)
![Formular](https://i.imgur.com/ZHwIX2s.png)

**Comment by aisbergde** [comment]
Das war also mein Fehler
