### ISSUE TITLE
unused variable

### ISSUE THREAD

**Issue by maddin200** [Thomas-Mielke-Software/EasyCash#9]
/ECTIFace/XMLite.cpp line 272:

LPTSTR _tcsenistr( LPCTSTR psz, LPCTSTR str, int len, int escape )
{
	LPTSTR pch = (LPTSTR)psz;
	LPTSTR prev_escape = NULL;
	LPTSTR des = (LPTSTR)str;  // <- not used
	int i = 0;
	
	while( pch && *pch )
	{
		if( escape != 0 && *pch == escape && prev_escape == NULL )
			prev_escape = pch;
		else
		{
			prev_escape = NULL;
			if( _tcsenicmp( pch, str, len, escape ) == 0 )
				return (LPTSTR)pch;
		}
		pch++;
	}
	return pch;
}

**Comment by thomiel** [comment]
ok...

https://github.com/Thomas-Mielke-Software/EasyCash/commit/23097d7c435b987702a4bf0415690f41bc03d80d

Ich nehme an, Du hast die xmlite-Datei für ein eigenes Projekt recycelt?

**Comment by maddin200** [comment]
nur files gescannt
